
- hosts: server1
  vars: 
  	port_number: "{{80}}"
 	image_name: "{{http_image}}"
 	docker_container_name: "{{web_server}}"
  
  tasks:
  - name: Install prerequisites for Docker repository
    apt:
      name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg2', 'software-properties-common']
      update_cache: yes

  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable

  - name: Install Docker CE
    apt:
      name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
      update_cache: yes

  - name: Install prerequisites for docker-compose
    apt:
      name: ['python3-pip', 'python3-setuptools', 'virtualenv']

  - name: Install docker-compose
    pip:
      name: docker-compose

  - name: Start Docker Service
    service:
     name: docker
     state: started

  - name: Creating Folder for website
    file:
     path: /root/Website
     state: directory

  - name: Copy website to work dir
    copy:
     src: "index.html" 
     dest: "/root/Website"
    ignore_errors: yes

  - name: Create Docker Image
    docker_image:
     name: "{{image_name"}}
     source: pull

  - name: Creat Docker Container
    docker_container:
     name: "{{docker_container_name}}"
     image: httpd
     state: started
     detach: true
     interactive: true
     ports:
     - "{{port_number}}"
     volumes:
     - /root/Website/:/usr/local/apache3/htdocs/
